name: i18n_talk_library
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.0-257.0.dev

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.2
  meta: ^1.14.0
  native_assets_cli:
    path: ../../native/pkgs/native_assets_cli
  native_toolchain_c:
    path: ../../native/pkgs/native_toolchain_c

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
