name: treeshaking_native_libs
description: Treeshake symbols by name from a native library.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  logging: ^1.1.1
  native_assets_cli: ^0.8.0
  native_toolchain_c: ^0.5.4
  meta: ^1.16.0
  record_use: ^0.3.0

dev_dependencies:
  ffigen: ^8.0.2
  lints: ^3.0.0
  test: ^1.23.1
